#
# Module manifest for module 'CosmosLite'
#
# Generated by: Jiri Formacek
#
# Generated on: 11.01.2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\CosmosLite.psm1'

# Version number of this module.
ModuleVersion = '3.2.0'

# Supported PSEditions
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module
GUID = '6ef617ca-11fe-4d2c-92dd-c9550ef97bc1'

# Author of this module
Author = 'Jiri Formacek'

# Company or vendor of this module
CompanyName = 'GreyCorbel Solutions'

# Copyright statement for this module
Copyright = '(c) 2022 - 2026 Jiri Formacek, GreyCorbel Solutions. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Provides commands that allow easy manipulation with data in Cosmos DB'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('CosmosLite.format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Assert-CosmosResult','Connect-Cosmos','Get-CosmosAccessToken','Get-CosmosCollectionPartitionKeyRanges','Get-CosmosConnection','Get-CosmosDocument','Invoke-CosmosQuery','Invoke-CosmosStoredProcedure','New-CosmosDocument','New-CosmosDocumentUpdate','New-CosmosUpdateOperation','Remove-CosmosDocument','Set-CosmosDocument','Set-CosmosRetryCount','Update-CosmosDocument')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList =     @()
# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('CosmosDB','PSEdition_Core','PSEdition_Desktop')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/GreyCorbel/CosmosLite/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/greycorbel/CosmosLite'

        # Prerelease string of this module
        Prerelease = 'beta2'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/GreyCorbel/CosmosLite/master/Icons/cosmosLite.png'

        # ReleaseNotes of this module
        # ReleaseNotes = ''
        ExternalModuleDependencies = @('AadAuthenticationFactory')

    } # End of PSData hashtable
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

    }
}






